/// <reference types="expo/types" />

// NOTE: This file should not be edited and should be committed alongside the rest
// of your project's source. It is generated by Expo and enables Expo's typed APIs.
